---
name: PART3 - CH3 - Self-Hosted Runner
on: 
  workflow_dispatch:
    inputs:
      self-hosted-runner:
        description: 'enter a runner name'
        required: true
        default: 'self-hosted-amzn'
jobs:
  build:
    name: Build on self-hosted
    runs-on: ${{ github.event.inputs.self-hosted-runner }}
    steps:
    - id: checkout
      name: Checkout 
      uses: actions/checkout@v2
    - id: setup-node
      name: Setup Node.js
      run: |
        cat /etc/*release
